eureka:
  client:
    regester-with-eureka: true
    fetch-regestry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

okta:
  oauth2:
    issuer: https://integrator-6702530.okta.com/oauth2/default
    audience: api://default
 
